### ISSUE TITLE
keyframe-effect-constructor.js:128 Uncaught TypeError: Failed to execute 'animate' on 'Element': 'function (a){return a}' is not a valid value for easing

### ISSUE THREAD

**Issue by triune** [web-animations/web-animations-next#492]
In Chrome 52 (Stable) this is the warning...

Specifying animation easing as a function is deprecated and all support will be removed in M54, around October 2016, at which point this will throw a TypeError. This warning may have been triggered by the Web Animations or Polymer polyfills. See http://crbug.com/601672 for details.

In Chrome 54 (dev) as of last week, this now throws a TypeError and breaks any Polymer application that relies on a neon-animation component.

`keyframe-effect-constructor.js:128 Uncaught TypeError: Failed to execute 'animate' on 'Element': 'function (a){return a}' is not a valid value for easing
    at Object.b.newUnderlyingAnimationForKeyframeEffect (https://dev.com/assets/bower_components/web-animations-js/web-animations-next-lite.min.js:16:7609)
    at b.Animation._rebuildUnderlyingAnimation (https://dev.com/assets/bower_components/web-animations-js/web-animations-next-lite.min.js:15:31941)
    at b.Animation (https://dev.com/assets/bower_components/web-animations-js/web-animations-next-lite.min.js:15:30984)
    at b.AnimationTimeline._play (https://dev.com/assets/bower_components/web-animations-js/web-animations-next-lite.min.js:15:30111)
    at Object.b.newUnderlyingAnimationForGroup (https://dev.com/assets/bower_components/web-animations-js/web-animations-next-lite.min.js:16:12228)
    at b.Animation._rebuildUnderlyingAnimation (https://dev.com/assets/bower_components/web-animations-js/web-animations-next-lite.min.js:15:32144)
    at b.Animation (https://dev.com/assets/bower_components/web-animations-js/web-animations-next-lite.min.js:15:30984)
    at b.AnimationTimeline._play (https://dev.com/assets/bower_components/web-animations-js/web-animations-next-lite.min.js:15:30111)
    at b.AnimationTimeline.play (https://dev.com/assets/bower_components/web-animations-js/web-animations-next-lite.min.js:15:30306)
    at HTMLElement._runAnimationEffects (https://dev.com/assets/bower_components/neon-animation/neon-animation-runner-behavior.html:62:32)b.newUnderlyingAnimationForKeyframeEffect @ keyframe-effect-constructor.js:128_rebuildUnderlyingAnimation @ web-animations-next-animation.js:86b.Animation @ web-animations-next-animation.js:35_play @ timeline.js:48b.newUnderlyingAnimationForGroup @ group-constructors.js:189_rebuildUnderlyingAnimation @ web-animations-next-animation.js:90b.Animation @ web-animations-next-animation.js:35_play @ timeline.js:48play @ timeline.js:65_runAnimationEffects @ neon-animation-runner-behavior.html:62playAnimation @ neon-animation-runner-behavior.html:87show @ (index):1672(anonymous function) @ (index):628(anonymous function) @ webcomponents-lite.min.js:12`

**Comment by triune** [comment]
Can be fixed by pulling in any of these versions...

https://github.com/web-animations/web-animations-js/tree/2.2.0
https://github.com/web-animations/web-animations-js/tree/2.1.5
https://github.com/web-animations/web-animations-js/tree/2.0.1
https://github.com/web-animations/web-animations-js/tree/1.0.8

Please close this issue.
